// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/open-telemetry/otel-arrow/go/api/experimental/arrow/v1 (interfaces: ArrowTracesServiceClient,ArrowTracesService_ArrowTracesClient,ArrowTracesServiceServer,ArrowTracesService_ArrowTracesServer,ArrowLogsServiceClient,ArrowLogsService_ArrowLogsClient,ArrowLogsServiceServer,ArrowLogsService_ArrowLogsServer,ArrowMetricsServiceClient,ArrowMetricsService_ArrowMetricsClient,ArrowMetricsServiceServer,ArrowMetricsService_ArrowMetricsServer,ArrowProfilesServiceClient,ArrowProfilesService_ArrowProfilesClient,ArrowProfilesServiceServer,ArrowProfilesService_ArrowProfilesServer)
//
// Generated by this command:
//
//	mockgen -package mock github.com/open-telemetry/otel-arrow/go/api/experimental/arrow/v1 ArrowTracesServiceClient,ArrowTracesService_ArrowTracesClient,ArrowTracesServiceServer,ArrowTracesService_ArrowTracesServer,ArrowLogsServiceClient,ArrowLogsService_ArrowLogsClient,ArrowLogsServiceServer,ArrowLogsService_ArrowLogsServer,ArrowMetricsServiceClient,ArrowMetricsService_ArrowMetricsClient,ArrowMetricsServiceServer,ArrowMetricsService_ArrowMetricsServer,ArrowProfilesServiceClient,ArrowProfilesService_ArrowProfilesClient,ArrowProfilesServiceServer,ArrowProfilesService_ArrowProfilesServer
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	v1 "github.com/open-telemetry/otel-arrow/go/api/experimental/arrow/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
)

// MockArrowTracesServiceClient is a mock of ArrowTracesServiceClient interface.
type MockArrowTracesServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockArrowTracesServiceClientMockRecorder
	isgomock struct{}
}

// MockArrowTracesServiceClientMockRecorder is the mock recorder for MockArrowTracesServiceClient.
type MockArrowTracesServiceClientMockRecorder struct {
	mock *MockArrowTracesServiceClient
}

// NewMockArrowTracesServiceClient creates a new mock instance.
func NewMockArrowTracesServiceClient(ctrl *gomock.Controller) *MockArrowTracesServiceClient {
	mock := &MockArrowTracesServiceClient{ctrl: ctrl}
	mock.recorder = &MockArrowTracesServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowTracesServiceClient) EXPECT() *MockArrowTracesServiceClientMockRecorder {
	return m.recorder
}

// ArrowTraces mocks base method.
func (m *MockArrowTracesServiceClient) ArrowTraces(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.BatchArrowRecords, v1.BatchStatus], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ArrowTraces", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[v1.BatchArrowRecords, v1.BatchStatus])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArrowTraces indicates an expected call of ArrowTraces.
func (mr *MockArrowTracesServiceClientMockRecorder) ArrowTraces(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArrowTraces", reflect.TypeOf((*MockArrowTracesServiceClient)(nil).ArrowTraces), varargs...)
}

// MockArrowTracesService_ArrowTracesClient is a mock of ArrowTracesService_ArrowTracesClient interface.
type MockArrowTracesService_ArrowTracesClient[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]
	isgomock struct{}
}

// MockArrowTracesService_ArrowTracesClientMockRecorder is the mock recorder for MockArrowTracesService_ArrowTracesClient.
type MockArrowTracesService_ArrowTracesClientMockRecorder[Req any, Res any] struct {
	mock *MockArrowTracesService_ArrowTracesClient[Req, Res]
}

// NewMockArrowTracesService_ArrowTracesClient creates a new mock instance.
func NewMockArrowTracesService_ArrowTracesClient[Req any, Res any](ctrl *gomock.Controller) *MockArrowTracesService_ArrowTracesClient[Req, Res] {
	mock := &MockArrowTracesService_ArrowTracesClient[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowTracesService_ArrowTracesClient[Req, Res]) EXPECT() *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockArrowTracesService_ArrowTracesClient[Req, Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockArrowTracesService_ArrowTracesClient[Req, Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockArrowTracesService_ArrowTracesClient[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockArrowTracesService_ArrowTracesClient[Req, Res])(nil).Context))
}

// Header mocks base method.
func (m *MockArrowTracesService_ArrowTracesClient[Req, Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockArrowTracesService_ArrowTracesClient[Req, Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockArrowTracesService_ArrowTracesClient[Req, Res]) Recv() (*v1.BatchStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.BatchStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockArrowTracesService_ArrowTracesClient[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockArrowTracesService_ArrowTracesClient[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockArrowTracesService_ArrowTracesClient[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockArrowTracesService_ArrowTracesClient[Req, Res]) Send(arg0 *v1.BatchArrowRecords) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockArrowTracesService_ArrowTracesClient[Req, Res])(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockArrowTracesService_ArrowTracesClient[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockArrowTracesService_ArrowTracesClient[Req, Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockArrowTracesService_ArrowTracesClient[Req, Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockArrowTracesService_ArrowTracesClientMockRecorder[Req, Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockArrowTracesService_ArrowTracesClient[Req, Res])(nil).Trailer))
}

// MockArrowTracesServiceServer is a mock of ArrowTracesServiceServer interface.
type MockArrowTracesServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockArrowTracesServiceServerMockRecorder
	isgomock struct{}
}

// MockArrowTracesServiceServerMockRecorder is the mock recorder for MockArrowTracesServiceServer.
type MockArrowTracesServiceServerMockRecorder struct {
	mock *MockArrowTracesServiceServer
}

// NewMockArrowTracesServiceServer creates a new mock instance.
func NewMockArrowTracesServiceServer(ctrl *gomock.Controller) *MockArrowTracesServiceServer {
	mock := &MockArrowTracesServiceServer{ctrl: ctrl}
	mock.recorder = &MockArrowTracesServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowTracesServiceServer) EXPECT() *MockArrowTracesServiceServerMockRecorder {
	return m.recorder
}

// ArrowTraces mocks base method.
func (m *MockArrowTracesServiceServer) ArrowTraces(arg0 grpc.BidiStreamingServer[v1.BatchArrowRecords, v1.BatchStatus]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArrowTraces", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArrowTraces indicates an expected call of ArrowTraces.
func (mr *MockArrowTracesServiceServerMockRecorder) ArrowTraces(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArrowTraces", reflect.TypeOf((*MockArrowTracesServiceServer)(nil).ArrowTraces), arg0)
}

// mustEmbedUnimplementedArrowTracesServiceServer mocks base method.
func (m *MockArrowTracesServiceServer) mustEmbedUnimplementedArrowTracesServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedArrowTracesServiceServer")
}

// mustEmbedUnimplementedArrowTracesServiceServer indicates an expected call of mustEmbedUnimplementedArrowTracesServiceServer.
func (mr *MockArrowTracesServiceServerMockRecorder) mustEmbedUnimplementedArrowTracesServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedArrowTracesServiceServer", reflect.TypeOf((*MockArrowTracesServiceServer)(nil).mustEmbedUnimplementedArrowTracesServiceServer))
}

// MockArrowTracesService_ArrowTracesServer is a mock of ArrowTracesService_ArrowTracesServer interface.
type MockArrowTracesService_ArrowTracesServer[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]
	isgomock struct{}
}

// MockArrowTracesService_ArrowTracesServerMockRecorder is the mock recorder for MockArrowTracesService_ArrowTracesServer.
type MockArrowTracesService_ArrowTracesServerMockRecorder[Req any, Res any] struct {
	mock *MockArrowTracesService_ArrowTracesServer[Req, Res]
}

// NewMockArrowTracesService_ArrowTracesServer creates a new mock instance.
func NewMockArrowTracesService_ArrowTracesServer[Req any, Res any](ctrl *gomock.Controller) *MockArrowTracesService_ArrowTracesServer[Req, Res] {
	mock := &MockArrowTracesService_ArrowTracesServer[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowTracesService_ArrowTracesServer[Req, Res]) EXPECT() *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockArrowTracesService_ArrowTracesServer[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockArrowTracesService_ArrowTracesServer[Req, Res])(nil).Context))
}

// Recv mocks base method.
func (m *MockArrowTracesService_ArrowTracesServer[Req, Res]) Recv() (*v1.BatchArrowRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.BatchArrowRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockArrowTracesService_ArrowTracesServer[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockArrowTracesService_ArrowTracesServer[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockArrowTracesService_ArrowTracesServer[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockArrowTracesService_ArrowTracesServer[Req, Res]) Send(arg0 *v1.BatchStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockArrowTracesService_ArrowTracesServer[Req, Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockArrowTracesService_ArrowTracesServer[Req, Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockArrowTracesService_ArrowTracesServer[Req, Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockArrowTracesService_ArrowTracesServer[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockArrowTracesService_ArrowTracesServer[Req, Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockArrowTracesService_ArrowTracesServer[Req, Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockArrowTracesService_ArrowTracesServer[Req, Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockArrowTracesService_ArrowTracesServer[Req, Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockArrowTracesService_ArrowTracesServerMockRecorder[Req, Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockArrowTracesService_ArrowTracesServer[Req, Res])(nil).SetTrailer), arg0)
}

// MockArrowLogsServiceClient is a mock of ArrowLogsServiceClient interface.
type MockArrowLogsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockArrowLogsServiceClientMockRecorder
	isgomock struct{}
}

// MockArrowLogsServiceClientMockRecorder is the mock recorder for MockArrowLogsServiceClient.
type MockArrowLogsServiceClientMockRecorder struct {
	mock *MockArrowLogsServiceClient
}

// NewMockArrowLogsServiceClient creates a new mock instance.
func NewMockArrowLogsServiceClient(ctrl *gomock.Controller) *MockArrowLogsServiceClient {
	mock := &MockArrowLogsServiceClient{ctrl: ctrl}
	mock.recorder = &MockArrowLogsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowLogsServiceClient) EXPECT() *MockArrowLogsServiceClientMockRecorder {
	return m.recorder
}

// ArrowLogs mocks base method.
func (m *MockArrowLogsServiceClient) ArrowLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.BatchArrowRecords, v1.BatchStatus], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ArrowLogs", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[v1.BatchArrowRecords, v1.BatchStatus])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArrowLogs indicates an expected call of ArrowLogs.
func (mr *MockArrowLogsServiceClientMockRecorder) ArrowLogs(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArrowLogs", reflect.TypeOf((*MockArrowLogsServiceClient)(nil).ArrowLogs), varargs...)
}

// MockArrowLogsService_ArrowLogsClient is a mock of ArrowLogsService_ArrowLogsClient interface.
type MockArrowLogsService_ArrowLogsClient[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]
	isgomock struct{}
}

// MockArrowLogsService_ArrowLogsClientMockRecorder is the mock recorder for MockArrowLogsService_ArrowLogsClient.
type MockArrowLogsService_ArrowLogsClientMockRecorder[Req any, Res any] struct {
	mock *MockArrowLogsService_ArrowLogsClient[Req, Res]
}

// NewMockArrowLogsService_ArrowLogsClient creates a new mock instance.
func NewMockArrowLogsService_ArrowLogsClient[Req any, Res any](ctrl *gomock.Controller) *MockArrowLogsService_ArrowLogsClient[Req, Res] {
	mock := &MockArrowLogsService_ArrowLogsClient[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowLogsService_ArrowLogsClient[Req, Res]) EXPECT() *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockArrowLogsService_ArrowLogsClient[Req, Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockArrowLogsService_ArrowLogsClient[Req, Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockArrowLogsService_ArrowLogsClient[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockArrowLogsService_ArrowLogsClient[Req, Res])(nil).Context))
}

// Header mocks base method.
func (m *MockArrowLogsService_ArrowLogsClient[Req, Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockArrowLogsService_ArrowLogsClient[Req, Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockArrowLogsService_ArrowLogsClient[Req, Res]) Recv() (*v1.BatchStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.BatchStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockArrowLogsService_ArrowLogsClient[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockArrowLogsService_ArrowLogsClient[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockArrowLogsService_ArrowLogsClient[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockArrowLogsService_ArrowLogsClient[Req, Res]) Send(arg0 *v1.BatchArrowRecords) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockArrowLogsService_ArrowLogsClient[Req, Res])(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockArrowLogsService_ArrowLogsClient[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockArrowLogsService_ArrowLogsClient[Req, Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockArrowLogsService_ArrowLogsClient[Req, Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockArrowLogsService_ArrowLogsClientMockRecorder[Req, Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockArrowLogsService_ArrowLogsClient[Req, Res])(nil).Trailer))
}

// MockArrowLogsServiceServer is a mock of ArrowLogsServiceServer interface.
type MockArrowLogsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockArrowLogsServiceServerMockRecorder
	isgomock struct{}
}

// MockArrowLogsServiceServerMockRecorder is the mock recorder for MockArrowLogsServiceServer.
type MockArrowLogsServiceServerMockRecorder struct {
	mock *MockArrowLogsServiceServer
}

// NewMockArrowLogsServiceServer creates a new mock instance.
func NewMockArrowLogsServiceServer(ctrl *gomock.Controller) *MockArrowLogsServiceServer {
	mock := &MockArrowLogsServiceServer{ctrl: ctrl}
	mock.recorder = &MockArrowLogsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowLogsServiceServer) EXPECT() *MockArrowLogsServiceServerMockRecorder {
	return m.recorder
}

// ArrowLogs mocks base method.
func (m *MockArrowLogsServiceServer) ArrowLogs(arg0 grpc.BidiStreamingServer[v1.BatchArrowRecords, v1.BatchStatus]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArrowLogs", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArrowLogs indicates an expected call of ArrowLogs.
func (mr *MockArrowLogsServiceServerMockRecorder) ArrowLogs(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArrowLogs", reflect.TypeOf((*MockArrowLogsServiceServer)(nil).ArrowLogs), arg0)
}

// mustEmbedUnimplementedArrowLogsServiceServer mocks base method.
func (m *MockArrowLogsServiceServer) mustEmbedUnimplementedArrowLogsServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedArrowLogsServiceServer")
}

// mustEmbedUnimplementedArrowLogsServiceServer indicates an expected call of mustEmbedUnimplementedArrowLogsServiceServer.
func (mr *MockArrowLogsServiceServerMockRecorder) mustEmbedUnimplementedArrowLogsServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedArrowLogsServiceServer", reflect.TypeOf((*MockArrowLogsServiceServer)(nil).mustEmbedUnimplementedArrowLogsServiceServer))
}

// MockArrowLogsService_ArrowLogsServer is a mock of ArrowLogsService_ArrowLogsServer interface.
type MockArrowLogsService_ArrowLogsServer[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]
	isgomock struct{}
}

// MockArrowLogsService_ArrowLogsServerMockRecorder is the mock recorder for MockArrowLogsService_ArrowLogsServer.
type MockArrowLogsService_ArrowLogsServerMockRecorder[Req any, Res any] struct {
	mock *MockArrowLogsService_ArrowLogsServer[Req, Res]
}

// NewMockArrowLogsService_ArrowLogsServer creates a new mock instance.
func NewMockArrowLogsService_ArrowLogsServer[Req any, Res any](ctrl *gomock.Controller) *MockArrowLogsService_ArrowLogsServer[Req, Res] {
	mock := &MockArrowLogsService_ArrowLogsServer[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowLogsService_ArrowLogsServer[Req, Res]) EXPECT() *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockArrowLogsService_ArrowLogsServer[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockArrowLogsService_ArrowLogsServer[Req, Res])(nil).Context))
}

// Recv mocks base method.
func (m *MockArrowLogsService_ArrowLogsServer[Req, Res]) Recv() (*v1.BatchArrowRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.BatchArrowRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockArrowLogsService_ArrowLogsServer[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockArrowLogsService_ArrowLogsServer[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockArrowLogsService_ArrowLogsServer[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockArrowLogsService_ArrowLogsServer[Req, Res]) Send(arg0 *v1.BatchStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockArrowLogsService_ArrowLogsServer[Req, Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockArrowLogsService_ArrowLogsServer[Req, Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockArrowLogsService_ArrowLogsServer[Req, Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockArrowLogsService_ArrowLogsServer[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockArrowLogsService_ArrowLogsServer[Req, Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockArrowLogsService_ArrowLogsServer[Req, Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockArrowLogsService_ArrowLogsServer[Req, Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockArrowLogsService_ArrowLogsServer[Req, Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockArrowLogsService_ArrowLogsServerMockRecorder[Req, Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockArrowLogsService_ArrowLogsServer[Req, Res])(nil).SetTrailer), arg0)
}

// MockArrowMetricsServiceClient is a mock of ArrowMetricsServiceClient interface.
type MockArrowMetricsServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockArrowMetricsServiceClientMockRecorder
	isgomock struct{}
}

// MockArrowMetricsServiceClientMockRecorder is the mock recorder for MockArrowMetricsServiceClient.
type MockArrowMetricsServiceClientMockRecorder struct {
	mock *MockArrowMetricsServiceClient
}

// NewMockArrowMetricsServiceClient creates a new mock instance.
func NewMockArrowMetricsServiceClient(ctrl *gomock.Controller) *MockArrowMetricsServiceClient {
	mock := &MockArrowMetricsServiceClient{ctrl: ctrl}
	mock.recorder = &MockArrowMetricsServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowMetricsServiceClient) EXPECT() *MockArrowMetricsServiceClientMockRecorder {
	return m.recorder
}

// ArrowMetrics mocks base method.
func (m *MockArrowMetricsServiceClient) ArrowMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.BatchArrowRecords, v1.BatchStatus], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ArrowMetrics", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[v1.BatchArrowRecords, v1.BatchStatus])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArrowMetrics indicates an expected call of ArrowMetrics.
func (mr *MockArrowMetricsServiceClientMockRecorder) ArrowMetrics(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArrowMetrics", reflect.TypeOf((*MockArrowMetricsServiceClient)(nil).ArrowMetrics), varargs...)
}

// MockArrowMetricsService_ArrowMetricsClient is a mock of ArrowMetricsService_ArrowMetricsClient interface.
type MockArrowMetricsService_ArrowMetricsClient[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]
	isgomock struct{}
}

// MockArrowMetricsService_ArrowMetricsClientMockRecorder is the mock recorder for MockArrowMetricsService_ArrowMetricsClient.
type MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req any, Res any] struct {
	mock *MockArrowMetricsService_ArrowMetricsClient[Req, Res]
}

// NewMockArrowMetricsService_ArrowMetricsClient creates a new mock instance.
func NewMockArrowMetricsService_ArrowMetricsClient[Req any, Res any](ctrl *gomock.Controller) *MockArrowMetricsService_ArrowMetricsClient[Req, Res] {
	mock := &MockArrowMetricsService_ArrowMetricsClient[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) EXPECT() *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsClient[Req, Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsClient[Req, Res])(nil).Context))
}

// Header mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsClient[Req, Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) Recv() (*v1.BatchStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.BatchStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsClient[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsClient[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) Send(arg0 *v1.BatchArrowRecords) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsClient[Req, Res])(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsClient[Req, Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsClient[Req, Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockArrowMetricsService_ArrowMetricsClientMockRecorder[Req, Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsClient[Req, Res])(nil).Trailer))
}

// MockArrowMetricsServiceServer is a mock of ArrowMetricsServiceServer interface.
type MockArrowMetricsServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockArrowMetricsServiceServerMockRecorder
	isgomock struct{}
}

// MockArrowMetricsServiceServerMockRecorder is the mock recorder for MockArrowMetricsServiceServer.
type MockArrowMetricsServiceServerMockRecorder struct {
	mock *MockArrowMetricsServiceServer
}

// NewMockArrowMetricsServiceServer creates a new mock instance.
func NewMockArrowMetricsServiceServer(ctrl *gomock.Controller) *MockArrowMetricsServiceServer {
	mock := &MockArrowMetricsServiceServer{ctrl: ctrl}
	mock.recorder = &MockArrowMetricsServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowMetricsServiceServer) EXPECT() *MockArrowMetricsServiceServerMockRecorder {
	return m.recorder
}

// ArrowMetrics mocks base method.
func (m *MockArrowMetricsServiceServer) ArrowMetrics(arg0 grpc.BidiStreamingServer[v1.BatchArrowRecords, v1.BatchStatus]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArrowMetrics", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArrowMetrics indicates an expected call of ArrowMetrics.
func (mr *MockArrowMetricsServiceServerMockRecorder) ArrowMetrics(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArrowMetrics", reflect.TypeOf((*MockArrowMetricsServiceServer)(nil).ArrowMetrics), arg0)
}

// mustEmbedUnimplementedArrowMetricsServiceServer mocks base method.
func (m *MockArrowMetricsServiceServer) mustEmbedUnimplementedArrowMetricsServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedArrowMetricsServiceServer")
}

// mustEmbedUnimplementedArrowMetricsServiceServer indicates an expected call of mustEmbedUnimplementedArrowMetricsServiceServer.
func (mr *MockArrowMetricsServiceServerMockRecorder) mustEmbedUnimplementedArrowMetricsServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedArrowMetricsServiceServer", reflect.TypeOf((*MockArrowMetricsServiceServer)(nil).mustEmbedUnimplementedArrowMetricsServiceServer))
}

// MockArrowMetricsService_ArrowMetricsServer is a mock of ArrowMetricsService_ArrowMetricsServer interface.
type MockArrowMetricsService_ArrowMetricsServer[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]
	isgomock struct{}
}

// MockArrowMetricsService_ArrowMetricsServerMockRecorder is the mock recorder for MockArrowMetricsService_ArrowMetricsServer.
type MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req any, Res any] struct {
	mock *MockArrowMetricsService_ArrowMetricsServer[Req, Res]
}

// NewMockArrowMetricsService_ArrowMetricsServer creates a new mock instance.
func NewMockArrowMetricsService_ArrowMetricsServer[Req any, Res any](ctrl *gomock.Controller) *MockArrowMetricsService_ArrowMetricsServer[Req, Res] {
	mock := &MockArrowMetricsService_ArrowMetricsServer[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) EXPECT() *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsServer[Req, Res])(nil).Context))
}

// Recv mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) Recv() (*v1.BatchArrowRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.BatchArrowRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsServer[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsServer[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) Send(arg0 *v1.BatchStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsServer[Req, Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsServer[Req, Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsServer[Req, Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsServer[Req, Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockArrowMetricsService_ArrowMetricsServer[Req, Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockArrowMetricsService_ArrowMetricsServerMockRecorder[Req, Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockArrowMetricsService_ArrowMetricsServer[Req, Res])(nil).SetTrailer), arg0)
}

// MockArrowProfilesServiceClient is a mock of ArrowProfilesServiceClient interface.
type MockArrowProfilesServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockArrowProfilesServiceClientMockRecorder
	isgomock struct{}
}

// MockArrowProfilesServiceClientMockRecorder is the mock recorder for MockArrowProfilesServiceClient.
type MockArrowProfilesServiceClientMockRecorder struct {
	mock *MockArrowProfilesServiceClient
}

// NewMockArrowProfilesServiceClient creates a new mock instance.
func NewMockArrowProfilesServiceClient(ctrl *gomock.Controller) *MockArrowProfilesServiceClient {
	mock := &MockArrowProfilesServiceClient{ctrl: ctrl}
	mock.recorder = &MockArrowProfilesServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowProfilesServiceClient) EXPECT() *MockArrowProfilesServiceClientMockRecorder {
	return m.recorder
}

// ArrowProfiles mocks base method.
func (m *MockArrowProfilesServiceClient) ArrowProfiles(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[v1.BatchArrowRecords, v1.BatchStatus], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ArrowProfiles", varargs...)
	ret0, _ := ret[0].(grpc.BidiStreamingClient[v1.BatchArrowRecords, v1.BatchStatus])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArrowProfiles indicates an expected call of ArrowProfiles.
func (mr *MockArrowProfilesServiceClientMockRecorder) ArrowProfiles(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArrowProfiles", reflect.TypeOf((*MockArrowProfilesServiceClient)(nil).ArrowProfiles), varargs...)
}

// MockArrowProfilesService_ArrowProfilesClient is a mock of ArrowProfilesService_ArrowProfilesClient interface.
type MockArrowProfilesService_ArrowProfilesClient[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]
	isgomock struct{}
}

// MockArrowProfilesService_ArrowProfilesClientMockRecorder is the mock recorder for MockArrowProfilesService_ArrowProfilesClient.
type MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req any, Res any] struct {
	mock *MockArrowProfilesService_ArrowProfilesClient[Req, Res]
}

// NewMockArrowProfilesService_ArrowProfilesClient creates a new mock instance.
func NewMockArrowProfilesService_ArrowProfilesClient[Req any, Res any](ctrl *gomock.Controller) *MockArrowProfilesService_ArrowProfilesClient[Req, Res] {
	mock := &MockArrowProfilesService_ArrowProfilesClient[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) EXPECT() *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res] {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesClient[Req, Res])(nil).CloseSend))
}

// Context mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesClient[Req, Res])(nil).Context))
}

// Header mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesClient[Req, Res])(nil).Header))
}

// Recv mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) Recv() (*v1.BatchStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.BatchStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesClient[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesClient[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) Send(arg0 *v1.BatchArrowRecords) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesClient[Req, Res])(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesClient[Req, Res])(nil).SendMsg), m)
}

// Trailer mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesClient[Req, Res]) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockArrowProfilesService_ArrowProfilesClientMockRecorder[Req, Res]) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesClient[Req, Res])(nil).Trailer))
}

// MockArrowProfilesServiceServer is a mock of ArrowProfilesServiceServer interface.
type MockArrowProfilesServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockArrowProfilesServiceServerMockRecorder
	isgomock struct{}
}

// MockArrowProfilesServiceServerMockRecorder is the mock recorder for MockArrowProfilesServiceServer.
type MockArrowProfilesServiceServerMockRecorder struct {
	mock *MockArrowProfilesServiceServer
}

// NewMockArrowProfilesServiceServer creates a new mock instance.
func NewMockArrowProfilesServiceServer(ctrl *gomock.Controller) *MockArrowProfilesServiceServer {
	mock := &MockArrowProfilesServiceServer{ctrl: ctrl}
	mock.recorder = &MockArrowProfilesServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowProfilesServiceServer) EXPECT() *MockArrowProfilesServiceServerMockRecorder {
	return m.recorder
}

// ArrowProfiles mocks base method.
func (m *MockArrowProfilesServiceServer) ArrowProfiles(arg0 grpc.BidiStreamingServer[v1.BatchArrowRecords, v1.BatchStatus]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArrowProfiles", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArrowProfiles indicates an expected call of ArrowProfiles.
func (mr *MockArrowProfilesServiceServerMockRecorder) ArrowProfiles(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArrowProfiles", reflect.TypeOf((*MockArrowProfilesServiceServer)(nil).ArrowProfiles), arg0)
}

// mustEmbedUnimplementedArrowProfilesServiceServer mocks base method.
func (m *MockArrowProfilesServiceServer) mustEmbedUnimplementedArrowProfilesServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedArrowProfilesServiceServer")
}

// mustEmbedUnimplementedArrowProfilesServiceServer indicates an expected call of mustEmbedUnimplementedArrowProfilesServiceServer.
func (mr *MockArrowProfilesServiceServerMockRecorder) mustEmbedUnimplementedArrowProfilesServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedArrowProfilesServiceServer", reflect.TypeOf((*MockArrowProfilesServiceServer)(nil).mustEmbedUnimplementedArrowProfilesServiceServer))
}

// MockArrowProfilesService_ArrowProfilesServer is a mock of ArrowProfilesService_ArrowProfilesServer interface.
type MockArrowProfilesService_ArrowProfilesServer[Req any, Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]
	isgomock struct{}
}

// MockArrowProfilesService_ArrowProfilesServerMockRecorder is the mock recorder for MockArrowProfilesService_ArrowProfilesServer.
type MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req any, Res any] struct {
	mock *MockArrowProfilesService_ArrowProfilesServer[Req, Res]
}

// NewMockArrowProfilesService_ArrowProfilesServer creates a new mock instance.
func NewMockArrowProfilesService_ArrowProfilesServer[Req any, Res any](ctrl *gomock.Controller) *MockArrowProfilesService_ArrowProfilesServer[Req, Res] {
	mock := &MockArrowProfilesService_ArrowProfilesServer[Req, Res]{ctrl: ctrl}
	mock.recorder = &MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) EXPECT() *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesServer[Req, Res])(nil).Context))
}

// Recv mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) Recv() (*v1.BatchArrowRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*v1.BatchArrowRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesServer[Req, Res])(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesServer[Req, Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) Send(arg0 *v1.BatchStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesServer[Req, Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesServer[Req, Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesServer[Req, Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesServer[Req, Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockArrowProfilesService_ArrowProfilesServer[Req, Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockArrowProfilesService_ArrowProfilesServerMockRecorder[Req, Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockArrowProfilesService_ArrowProfilesServer[Req, Res])(nil).SetTrailer), arg0)
}
