// This protocol specifies the services and messages utilized by the OTel Arrow
// Protocol. It extends the OTLP protocol by representing OTLP entities in a
// columnar manner using Apache Arrow. The primary objective of this new
// protocol is to optimize transport efficiency in terms of compression (phase 1),
// memory, and CPU usage (phase 2).
//
// Note: This protocol is still experimental and subject to change.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: opentelemetry/proto/experimental/arrow/v1/arrow_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enumeration of all the OTel Arrow payload types currently supported by the
// OTel Arrow protocol.
type ArrowPayloadType int32

const (
	ArrowPayloadType_UNKNOWN ArrowPayloadType = 0
	// A payload representing a collection of resource attributes.
	ArrowPayloadType_RESOURCE_ATTRS ArrowPayloadType = 1
	// A payload representing a collection of scope attributes.
	ArrowPayloadType_SCOPE_ATTRS ArrowPayloadType = 2
	// A set of payloads representing a collection of metrics.
	ArrowPayloadType_UNIVARIATE_METRICS              ArrowPayloadType = 10 // Univariate metric payload
	ArrowPayloadType_NUMBER_DATA_POINTS              ArrowPayloadType = 11
	ArrowPayloadType_SUMMARY_DATA_POINTS             ArrowPayloadType = 12
	ArrowPayloadType_HISTOGRAM_DATA_POINTS           ArrowPayloadType = 13
	ArrowPayloadType_EXP_HISTOGRAM_DATA_POINTS       ArrowPayloadType = 14
	ArrowPayloadType_NUMBER_DP_ATTRS                 ArrowPayloadType = 15
	ArrowPayloadType_SUMMARY_DP_ATTRS                ArrowPayloadType = 16
	ArrowPayloadType_HISTOGRAM_DP_ATTRS              ArrowPayloadType = 17
	ArrowPayloadType_EXP_HISTOGRAM_DP_ATTRS          ArrowPayloadType = 18
	ArrowPayloadType_NUMBER_DP_EXEMPLARS             ArrowPayloadType = 19
	ArrowPayloadType_HISTOGRAM_DP_EXEMPLARS          ArrowPayloadType = 20
	ArrowPayloadType_EXP_HISTOGRAM_DP_EXEMPLARS      ArrowPayloadType = 21
	ArrowPayloadType_NUMBER_DP_EXEMPLAR_ATTRS        ArrowPayloadType = 22
	ArrowPayloadType_HISTOGRAM_DP_EXEMPLAR_ATTRS     ArrowPayloadType = 23
	ArrowPayloadType_EXP_HISTOGRAM_DP_EXEMPLAR_ATTRS ArrowPayloadType = 24
	ArrowPayloadType_MULTIVARIATE_METRICS            ArrowPayloadType = 25 // Multivariate metric payload
	ArrowPayloadType_METRIC_ATTRS                    ArrowPayloadType = 26
	// A set of payloads representing a collection of logs.
	ArrowPayloadType_LOGS      ArrowPayloadType = 30
	ArrowPayloadType_LOG_ATTRS ArrowPayloadType = 31
	// A set of payloads representing a collection of traces.
	ArrowPayloadType_SPANS            ArrowPayloadType = 40
	ArrowPayloadType_SPAN_ATTRS       ArrowPayloadType = 41
	ArrowPayloadType_SPAN_EVENTS      ArrowPayloadType = 42
	ArrowPayloadType_SPAN_LINKS       ArrowPayloadType = 43
	ArrowPayloadType_SPAN_EVENT_ATTRS ArrowPayloadType = 44
	ArrowPayloadType_SPAN_LINK_ATTRS  ArrowPayloadType = 45
	// A set of payloads representing a collection of profiles.
	ArrowPayloadType_PROFILES        ArrowPayloadType = 50
	ArrowPayloadType_SAMPLE          ArrowPayloadType = 51
	ArrowPayloadType_MAPPING_TABLE   ArrowPayloadType = 52
	ArrowPayloadType_LOCATION_TABLE  ArrowPayloadType = 53
	ArrowPayloadType_FUNCTION_TABLE  ArrowPayloadType = 54
	ArrowPayloadType_LINK_TABLE      ArrowPayloadType = 55
	ArrowPayloadType_STRING_TABLE    ArrowPayloadType = 56
	ArrowPayloadType_ATTRIBUTE_TABLE ArrowPayloadType = 57
	ArrowPayloadType_ATTRIBUTE_UNITS ArrowPayloadType = 58
)

// Enum value maps for ArrowPayloadType.
var (
	ArrowPayloadType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "RESOURCE_ATTRS",
		2:  "SCOPE_ATTRS",
		10: "UNIVARIATE_METRICS",
		11: "NUMBER_DATA_POINTS",
		12: "SUMMARY_DATA_POINTS",
		13: "HISTOGRAM_DATA_POINTS",
		14: "EXP_HISTOGRAM_DATA_POINTS",
		15: "NUMBER_DP_ATTRS",
		16: "SUMMARY_DP_ATTRS",
		17: "HISTOGRAM_DP_ATTRS",
		18: "EXP_HISTOGRAM_DP_ATTRS",
		19: "NUMBER_DP_EXEMPLARS",
		20: "HISTOGRAM_DP_EXEMPLARS",
		21: "EXP_HISTOGRAM_DP_EXEMPLARS",
		22: "NUMBER_DP_EXEMPLAR_ATTRS",
		23: "HISTOGRAM_DP_EXEMPLAR_ATTRS",
		24: "EXP_HISTOGRAM_DP_EXEMPLAR_ATTRS",
		25: "MULTIVARIATE_METRICS",
		26: "METRIC_ATTRS",
		30: "LOGS",
		31: "LOG_ATTRS",
		40: "SPANS",
		41: "SPAN_ATTRS",
		42: "SPAN_EVENTS",
		43: "SPAN_LINKS",
		44: "SPAN_EVENT_ATTRS",
		45: "SPAN_LINK_ATTRS",
		50: "PROFILES",
		51: "SAMPLE",
		52: "MAPPING_TABLE",
		53: "LOCATION_TABLE",
		54: "FUNCTION_TABLE",
		55: "LINK_TABLE",
		56: "STRING_TABLE",
		57: "ATTRIBUTE_TABLE",
		58: "ATTRIBUTE_UNITS",
	}
	ArrowPayloadType_value = map[string]int32{
		"UNKNOWN":                         0,
		"RESOURCE_ATTRS":                  1,
		"SCOPE_ATTRS":                     2,
		"UNIVARIATE_METRICS":              10,
		"NUMBER_DATA_POINTS":              11,
		"SUMMARY_DATA_POINTS":             12,
		"HISTOGRAM_DATA_POINTS":           13,
		"EXP_HISTOGRAM_DATA_POINTS":       14,
		"NUMBER_DP_ATTRS":                 15,
		"SUMMARY_DP_ATTRS":                16,
		"HISTOGRAM_DP_ATTRS":              17,
		"EXP_HISTOGRAM_DP_ATTRS":          18,
		"NUMBER_DP_EXEMPLARS":             19,
		"HISTOGRAM_DP_EXEMPLARS":          20,
		"EXP_HISTOGRAM_DP_EXEMPLARS":      21,
		"NUMBER_DP_EXEMPLAR_ATTRS":        22,
		"HISTOGRAM_DP_EXEMPLAR_ATTRS":     23,
		"EXP_HISTOGRAM_DP_EXEMPLAR_ATTRS": 24,
		"MULTIVARIATE_METRICS":            25,
		"METRIC_ATTRS":                    26,
		"LOGS":                            30,
		"LOG_ATTRS":                       31,
		"SPANS":                           40,
		"SPAN_ATTRS":                      41,
		"SPAN_EVENTS":                     42,
		"SPAN_LINKS":                      43,
		"SPAN_EVENT_ATTRS":                44,
		"SPAN_LINK_ATTRS":                 45,
		"PROFILES":                        50,
		"SAMPLE":                          51,
		"MAPPING_TABLE":                   52,
		"LOCATION_TABLE":                  53,
		"FUNCTION_TABLE":                  54,
		"LINK_TABLE":                      55,
		"STRING_TABLE":                    56,
		"ATTRIBUTE_TABLE":                 57,
		"ATTRIBUTE_UNITS":                 58,
	}
)

func (x ArrowPayloadType) Enum() *ArrowPayloadType {
	p := new(ArrowPayloadType)
	*p = x
	return p
}

func (x ArrowPayloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArrowPayloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_enumTypes[0].Descriptor()
}

func (ArrowPayloadType) Type() protoreflect.EnumType {
	return &file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_enumTypes[0]
}

func (x ArrowPayloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArrowPayloadType.Descriptor instead.
func (ArrowPayloadType) EnumDescriptor() ([]byte, []int) {
	return file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescGZIP(), []int{0}
}

// StatusCode carries certain known meanings in Arrow.  Values match
// the gRPC code space, see https://grpc.io/docs/guides/status-codes/.
type StatusCode int32

const (
	StatusCode_OK                 StatusCode = 0
	StatusCode_CANCELED           StatusCode = 1
	StatusCode_INVALID_ARGUMENT   StatusCode = 3
	StatusCode_DEADLINE_EXCEEDED  StatusCode = 4
	StatusCode_PERMISSION_DENIED  StatusCode = 7
	StatusCode_RESOURCE_EXHAUSTED StatusCode = 8
	StatusCode_ABORTED            StatusCode = 10
	StatusCode_INTERNAL           StatusCode = 13
	StatusCode_UNAVAILABLE        StatusCode = 14
	StatusCode_UNAUTHENTICATED    StatusCode = 16
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:  "OK",
		1:  "CANCELED",
		3:  "INVALID_ARGUMENT",
		4:  "DEADLINE_EXCEEDED",
		7:  "PERMISSION_DENIED",
		8:  "RESOURCE_EXHAUSTED",
		10: "ABORTED",
		13: "INTERNAL",
		14: "UNAVAILABLE",
		16: "UNAUTHENTICATED",
	}
	StatusCode_value = map[string]int32{
		"OK":                 0,
		"CANCELED":           1,
		"INVALID_ARGUMENT":   3,
		"DEADLINE_EXCEEDED":  4,
		"PERMISSION_DENIED":  7,
		"RESOURCE_EXHAUSTED": 8,
		"ABORTED":            10,
		"INTERNAL":           13,
		"UNAVAILABLE":        14,
		"UNAUTHENTICATED":    16,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_enumTypes[1].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_enumTypes[1]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescGZIP(), []int{1}
}

// A message sent by an exporter to a collector containing a batch of Arrow
// records.
type BatchArrowRecords struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [mandatory] Batch ID. Must be unique in the context of the stream.
	BatchId int64 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// [mandatory] A collection of payloads containing the data of the batch.
	ArrowPayloads []*ArrowPayload `protobuf:"bytes,2,rep,name=arrow_payloads,json=arrowPayloads,proto3" json:"arrow_payloads,omitempty"`
	// [optional] Headers associated with this batch, encoded using hpack.
	Headers       []byte `protobuf:"bytes,3,opt,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchArrowRecords) Reset() {
	*x = BatchArrowRecords{}
	mi := &file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchArrowRecords) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchArrowRecords) ProtoMessage() {}

func (x *BatchArrowRecords) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchArrowRecords.ProtoReflect.Descriptor instead.
func (*BatchArrowRecords) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescGZIP(), []int{0}
}

func (x *BatchArrowRecords) GetBatchId() int64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *BatchArrowRecords) GetArrowPayloads() []*ArrowPayload {
	if x != nil {
		return x.ArrowPayloads
	}
	return nil
}

func (x *BatchArrowRecords) GetHeaders() []byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Represents a batch of OTel Arrow entities.
type ArrowPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// [mandatory] A canonical ID representing the schema of the Arrow Record.
	// This ID is used on the consumer side to determine the IPC reader to use
	// for interpreting the corresponding record. For any NEW `schema_id`, the
	// consumer must:
	// 1) close the current IPC reader,
	// 2) create a new IPC reader in order to interpret the new schema,
	// dictionaries, and corresponding data.
	SchemaId string `protobuf:"bytes,1,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	// [mandatory] Type of the OTel Arrow payload.
	Type ArrowPayloadType `protobuf:"varint,2,opt,name=type,proto3,enum=opentelemetry.proto.experimental.arrow.v1.ArrowPayloadType" json:"type,omitempty"`
	// [mandatory] Serialized Arrow Record Batch
	// For a description of the Arrow IPC format see:
	// https://arrow.apache.org/docs/format/Columnar.html#serialization-and-interprocess-communication-ipc
	Record        []byte `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrowPayload) Reset() {
	*x = ArrowPayload{}
	mi := &file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrowPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrowPayload) ProtoMessage() {}

func (x *ArrowPayload) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrowPayload.ProtoReflect.Descriptor instead.
func (*ArrowPayload) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescGZIP(), []int{1}
}

func (x *ArrowPayload) GetSchemaId() string {
	if x != nil {
		return x.SchemaId
	}
	return ""
}

func (x *ArrowPayload) GetType() ArrowPayloadType {
	if x != nil {
		return x.Type
	}
	return ArrowPayloadType_UNKNOWN
}

func (x *ArrowPayload) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

// A message sent by a Collector to the exporter that opened the data stream.
type BatchStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       int64                  `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	StatusCode    StatusCode             `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3,enum=opentelemetry.proto.experimental.arrow.v1.StatusCode" json:"status_code,omitempty"`
	StatusMessage string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchStatus) Reset() {
	*x = BatchStatus{}
	mi := &file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchStatus) ProtoMessage() {}

func (x *BatchStatus) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchStatus.ProtoReflect.Descriptor instead.
func (*BatchStatus) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescGZIP(), []int{2}
}

func (x *BatchStatus) GetBatchId() int64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *BatchStatus) GetStatusCode() StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return StatusCode_OK
}

func (x *BatchStatus) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto protoreflect.FileDescriptor

const file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDesc = "" +
	"\n" +
	"=opentelemetry/proto/experimental/arrow/v1/arrow_service.proto\x12)opentelemetry.proto.experimental.arrow.v1\"\xa8\x01\n" +
	"\x11BatchArrowRecords\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x03R\abatchId\x12^\n" +
	"\x0earrow_payloads\x18\x02 \x03(\v27.opentelemetry.proto.experimental.arrow.v1.ArrowPayloadR\rarrowPayloads\x12\x18\n" +
	"\aheaders\x18\x03 \x01(\fR\aheaders\"\x94\x01\n" +
	"\fArrowPayload\x12\x1b\n" +
	"\tschema_id\x18\x01 \x01(\tR\bschemaId\x12O\n" +
	"\x04type\x18\x02 \x01(\x0e2;.opentelemetry.proto.experimental.arrow.v1.ArrowPayloadTypeR\x04type\x12\x16\n" +
	"\x06record\x18\x03 \x01(\fR\x06record\"\xa7\x01\n" +
	"\vBatchStatus\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x03R\abatchId\x12V\n" +
	"\vstatus_code\x18\x02 \x01(\x0e25.opentelemetry.proto.experimental.arrow.v1.StatusCodeR\n" +
	"statusCode\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage*\xac\x06\n" +
	"\x10ArrowPayloadType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRESOURCE_ATTRS\x10\x01\x12\x0f\n" +
	"\vSCOPE_ATTRS\x10\x02\x12\x16\n" +
	"\x12UNIVARIATE_METRICS\x10\n" +
	"\x12\x16\n" +
	"\x12NUMBER_DATA_POINTS\x10\v\x12\x17\n" +
	"\x13SUMMARY_DATA_POINTS\x10\f\x12\x19\n" +
	"\x15HISTOGRAM_DATA_POINTS\x10\r\x12\x1d\n" +
	"\x19EXP_HISTOGRAM_DATA_POINTS\x10\x0e\x12\x13\n" +
	"\x0fNUMBER_DP_ATTRS\x10\x0f\x12\x14\n" +
	"\x10SUMMARY_DP_ATTRS\x10\x10\x12\x16\n" +
	"\x12HISTOGRAM_DP_ATTRS\x10\x11\x12\x1a\n" +
	"\x16EXP_HISTOGRAM_DP_ATTRS\x10\x12\x12\x17\n" +
	"\x13NUMBER_DP_EXEMPLARS\x10\x13\x12\x1a\n" +
	"\x16HISTOGRAM_DP_EXEMPLARS\x10\x14\x12\x1e\n" +
	"\x1aEXP_HISTOGRAM_DP_EXEMPLARS\x10\x15\x12\x1c\n" +
	"\x18NUMBER_DP_EXEMPLAR_ATTRS\x10\x16\x12\x1f\n" +
	"\x1bHISTOGRAM_DP_EXEMPLAR_ATTRS\x10\x17\x12#\n" +
	"\x1fEXP_HISTOGRAM_DP_EXEMPLAR_ATTRS\x10\x18\x12\x18\n" +
	"\x14MULTIVARIATE_METRICS\x10\x19\x12\x10\n" +
	"\fMETRIC_ATTRS\x10\x1a\x12\b\n" +
	"\x04LOGS\x10\x1e\x12\r\n" +
	"\tLOG_ATTRS\x10\x1f\x12\t\n" +
	"\x05SPANS\x10(\x12\x0e\n" +
	"\n" +
	"SPAN_ATTRS\x10)\x12\x0f\n" +
	"\vSPAN_EVENTS\x10*\x12\x0e\n" +
	"\n" +
	"SPAN_LINKS\x10+\x12\x14\n" +
	"\x10SPAN_EVENT_ATTRS\x10,\x12\x13\n" +
	"\x0fSPAN_LINK_ATTRS\x10-\x12\f\n" +
	"\bPROFILES\x102\x12\n" +
	"\n" +
	"\x06SAMPLE\x103\x12\x11\n" +
	"\rMAPPING_TABLE\x104\x12\x12\n" +
	"\x0eLOCATION_TABLE\x105\x12\x12\n" +
	"\x0eFUNCTION_TABLE\x106\x12\x0e\n" +
	"\n" +
	"LINK_TABLE\x107\x12\x10\n" +
	"\fSTRING_TABLE\x108\x12\x13\n" +
	"\x0fATTRIBUTE_TABLE\x109\x12\x13\n" +
	"\x0fATTRIBUTE_UNITS\x10:*\xbf\x01\n" +
	"\n" +
	"StatusCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\f\n" +
	"\bCANCELED\x10\x01\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x03\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x04\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\a\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\b\x12\v\n" +
	"\aABORTED\x10\n" +
	"\x12\f\n" +
	"\bINTERNAL\x10\r\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x0e\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x102\xa0\x01\n" +
	"\x12ArrowTracesService\x12\x89\x01\n" +
	"\vArrowTraces\x12<.opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords\x1a6.opentelemetry.proto.experimental.arrow.v1.BatchStatus\"\x00(\x010\x012\x9c\x01\n" +
	"\x10ArrowLogsService\x12\x87\x01\n" +
	"\tArrowLogs\x12<.opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords\x1a6.opentelemetry.proto.experimental.arrow.v1.BatchStatus\"\x00(\x010\x012\xa2\x01\n" +
	"\x13ArrowMetricsService\x12\x8a\x01\n" +
	"\fArrowMetrics\x12<.opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords\x1a6.opentelemetry.proto.experimental.arrow.v1.BatchStatus\"\x00(\x010\x012\xa4\x01\n" +
	"\x14ArrowProfilesService\x12\x8b\x01\n" +
	"\rArrowProfiles\x12<.opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords\x1a6.opentelemetry.proto.experimental.arrow.v1.BatchStatus\"\x00(\x010\x01B\x86\x01\n" +
	",io.opentelemetry.proto.experimental.arrow.v1B\x11ArrowServiceProtoP\x01ZAgithub.com/open-telemetry/otel-arrow/go/api/experimental/arrow/v1b\x06proto3"

var (
	file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescOnce sync.Once
	file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescData []byte
)

func file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescGZIP() []byte {
	file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescOnce.Do(func() {
		file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDesc), len(file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDesc)))
	})
	return file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDescData
}

var file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_goTypes = []any{
	(ArrowPayloadType)(0),     // 0: opentelemetry.proto.experimental.arrow.v1.ArrowPayloadType
	(StatusCode)(0),           // 1: opentelemetry.proto.experimental.arrow.v1.StatusCode
	(*BatchArrowRecords)(nil), // 2: opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords
	(*ArrowPayload)(nil),      // 3: opentelemetry.proto.experimental.arrow.v1.ArrowPayload
	(*BatchStatus)(nil),       // 4: opentelemetry.proto.experimental.arrow.v1.BatchStatus
}
var file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_depIdxs = []int32{
	3, // 0: opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords.arrow_payloads:type_name -> opentelemetry.proto.experimental.arrow.v1.ArrowPayload
	0, // 1: opentelemetry.proto.experimental.arrow.v1.ArrowPayload.type:type_name -> opentelemetry.proto.experimental.arrow.v1.ArrowPayloadType
	1, // 2: opentelemetry.proto.experimental.arrow.v1.BatchStatus.status_code:type_name -> opentelemetry.proto.experimental.arrow.v1.StatusCode
	2, // 3: opentelemetry.proto.experimental.arrow.v1.ArrowTracesService.ArrowTraces:input_type -> opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords
	2, // 4: opentelemetry.proto.experimental.arrow.v1.ArrowLogsService.ArrowLogs:input_type -> opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords
	2, // 5: opentelemetry.proto.experimental.arrow.v1.ArrowMetricsService.ArrowMetrics:input_type -> opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords
	2, // 6: opentelemetry.proto.experimental.arrow.v1.ArrowProfilesService.ArrowProfiles:input_type -> opentelemetry.proto.experimental.arrow.v1.BatchArrowRecords
	4, // 7: opentelemetry.proto.experimental.arrow.v1.ArrowTracesService.ArrowTraces:output_type -> opentelemetry.proto.experimental.arrow.v1.BatchStatus
	4, // 8: opentelemetry.proto.experimental.arrow.v1.ArrowLogsService.ArrowLogs:output_type -> opentelemetry.proto.experimental.arrow.v1.BatchStatus
	4, // 9: opentelemetry.proto.experimental.arrow.v1.ArrowMetricsService.ArrowMetrics:output_type -> opentelemetry.proto.experimental.arrow.v1.BatchStatus
	4, // 10: opentelemetry.proto.experimental.arrow.v1.ArrowProfilesService.ArrowProfiles:output_type -> opentelemetry.proto.experimental.arrow.v1.BatchStatus
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_init() }
func file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_init() {
	if File_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDesc), len(file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_goTypes,
		DependencyIndexes: file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_depIdxs,
		EnumInfos:         file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_enumTypes,
		MessageInfos:      file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_msgTypes,
	}.Build()
	File_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto = out.File
	file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_goTypes = nil
	file_opentelemetry_proto_experimental_arrow_v1_arrow_service_proto_depIdxs = nil
}
