// This protocol specifies the services and messages utilized by the OTel Arrow
// Protocol. It extends the OTLP protocol by representing OTLP entities in a
// columnar manner using Apache Arrow. The primary objective of this new
// protocol is to optimize transport efficiency in terms of compression (phase 1),
// memory, and CPU usage (phase 2).
//
// Note: This protocol is still experimental and subject to change.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: opentelemetry/proto/experimental/arrow/v1/arrow_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArrowTracesService_ArrowTraces_FullMethodName = "/opentelemetry.proto.experimental.arrow.v1.ArrowTracesService/ArrowTraces"
)

// ArrowTracesServiceClient is the client API for ArrowTracesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArrowTracesService is a traces-only Arrow stream.
type ArrowTracesServiceClient interface {
	ArrowTraces(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus], error)
}

type arrowTracesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArrowTracesServiceClient(cc grpc.ClientConnInterface) ArrowTracesServiceClient {
	return &arrowTracesServiceClient{cc}
}

func (c *arrowTracesServiceClient) ArrowTraces(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArrowTracesService_ServiceDesc.Streams[0], ArrowTracesService_ArrowTraces_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchArrowRecords, BatchStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArrowTracesService_ArrowTracesClient = grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus]

// ArrowTracesServiceServer is the server API for ArrowTracesService service.
// All implementations must embed UnimplementedArrowTracesServiceServer
// for forward compatibility.
//
// ArrowTracesService is a traces-only Arrow stream.
type ArrowTracesServiceServer interface {
	ArrowTraces(grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]) error
	mustEmbedUnimplementedArrowTracesServiceServer()
}

// UnimplementedArrowTracesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArrowTracesServiceServer struct{}

func (UnimplementedArrowTracesServiceServer) ArrowTraces(grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]) error {
	return status.Errorf(codes.Unimplemented, "method ArrowTraces not implemented")
}
func (UnimplementedArrowTracesServiceServer) mustEmbedUnimplementedArrowTracesServiceServer() {}
func (UnimplementedArrowTracesServiceServer) testEmbeddedByValue()                            {}

// UnsafeArrowTracesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArrowTracesServiceServer will
// result in compilation errors.
type UnsafeArrowTracesServiceServer interface {
	mustEmbedUnimplementedArrowTracesServiceServer()
}

func RegisterArrowTracesServiceServer(s grpc.ServiceRegistrar, srv ArrowTracesServiceServer) {
	// If the following call pancis, it indicates UnimplementedArrowTracesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArrowTracesService_ServiceDesc, srv)
}

func _ArrowTracesService_ArrowTraces_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArrowTracesServiceServer).ArrowTraces(&grpc.GenericServerStream[BatchArrowRecords, BatchStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArrowTracesService_ArrowTracesServer = grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]

// ArrowTracesService_ServiceDesc is the grpc.ServiceDesc for ArrowTracesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArrowTracesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opentelemetry.proto.experimental.arrow.v1.ArrowTracesService",
	HandlerType: (*ArrowTracesServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ArrowTraces",
			Handler:       _ArrowTracesService_ArrowTraces_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "opentelemetry/proto/experimental/arrow/v1/arrow_service.proto",
}

const (
	ArrowLogsService_ArrowLogs_FullMethodName = "/opentelemetry.proto.experimental.arrow.v1.ArrowLogsService/ArrowLogs"
)

// ArrowLogsServiceClient is the client API for ArrowLogsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArrowTracesService is a logs-only Arrow stream.
type ArrowLogsServiceClient interface {
	ArrowLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus], error)
}

type arrowLogsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArrowLogsServiceClient(cc grpc.ClientConnInterface) ArrowLogsServiceClient {
	return &arrowLogsServiceClient{cc}
}

func (c *arrowLogsServiceClient) ArrowLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArrowLogsService_ServiceDesc.Streams[0], ArrowLogsService_ArrowLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchArrowRecords, BatchStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArrowLogsService_ArrowLogsClient = grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus]

// ArrowLogsServiceServer is the server API for ArrowLogsService service.
// All implementations must embed UnimplementedArrowLogsServiceServer
// for forward compatibility.
//
// ArrowTracesService is a logs-only Arrow stream.
type ArrowLogsServiceServer interface {
	ArrowLogs(grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]) error
	mustEmbedUnimplementedArrowLogsServiceServer()
}

// UnimplementedArrowLogsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArrowLogsServiceServer struct{}

func (UnimplementedArrowLogsServiceServer) ArrowLogs(grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]) error {
	return status.Errorf(codes.Unimplemented, "method ArrowLogs not implemented")
}
func (UnimplementedArrowLogsServiceServer) mustEmbedUnimplementedArrowLogsServiceServer() {}
func (UnimplementedArrowLogsServiceServer) testEmbeddedByValue()                          {}

// UnsafeArrowLogsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArrowLogsServiceServer will
// result in compilation errors.
type UnsafeArrowLogsServiceServer interface {
	mustEmbedUnimplementedArrowLogsServiceServer()
}

func RegisterArrowLogsServiceServer(s grpc.ServiceRegistrar, srv ArrowLogsServiceServer) {
	// If the following call pancis, it indicates UnimplementedArrowLogsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArrowLogsService_ServiceDesc, srv)
}

func _ArrowLogsService_ArrowLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArrowLogsServiceServer).ArrowLogs(&grpc.GenericServerStream[BatchArrowRecords, BatchStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArrowLogsService_ArrowLogsServer = grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]

// ArrowLogsService_ServiceDesc is the grpc.ServiceDesc for ArrowLogsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArrowLogsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opentelemetry.proto.experimental.arrow.v1.ArrowLogsService",
	HandlerType: (*ArrowLogsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ArrowLogs",
			Handler:       _ArrowLogsService_ArrowLogs_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "opentelemetry/proto/experimental/arrow/v1/arrow_service.proto",
}

const (
	ArrowMetricsService_ArrowMetrics_FullMethodName = "/opentelemetry.proto.experimental.arrow.v1.ArrowMetricsService/ArrowMetrics"
)

// ArrowMetricsServiceClient is the client API for ArrowMetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArrowTracesService is a metrics-only Arrow stream.
type ArrowMetricsServiceClient interface {
	ArrowMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus], error)
}

type arrowMetricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArrowMetricsServiceClient(cc grpc.ClientConnInterface) ArrowMetricsServiceClient {
	return &arrowMetricsServiceClient{cc}
}

func (c *arrowMetricsServiceClient) ArrowMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArrowMetricsService_ServiceDesc.Streams[0], ArrowMetricsService_ArrowMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchArrowRecords, BatchStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArrowMetricsService_ArrowMetricsClient = grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus]

// ArrowMetricsServiceServer is the server API for ArrowMetricsService service.
// All implementations must embed UnimplementedArrowMetricsServiceServer
// for forward compatibility.
//
// ArrowTracesService is a metrics-only Arrow stream.
type ArrowMetricsServiceServer interface {
	ArrowMetrics(grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]) error
	mustEmbedUnimplementedArrowMetricsServiceServer()
}

// UnimplementedArrowMetricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArrowMetricsServiceServer struct{}

func (UnimplementedArrowMetricsServiceServer) ArrowMetrics(grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]) error {
	return status.Errorf(codes.Unimplemented, "method ArrowMetrics not implemented")
}
func (UnimplementedArrowMetricsServiceServer) mustEmbedUnimplementedArrowMetricsServiceServer() {}
func (UnimplementedArrowMetricsServiceServer) testEmbeddedByValue()                             {}

// UnsafeArrowMetricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArrowMetricsServiceServer will
// result in compilation errors.
type UnsafeArrowMetricsServiceServer interface {
	mustEmbedUnimplementedArrowMetricsServiceServer()
}

func RegisterArrowMetricsServiceServer(s grpc.ServiceRegistrar, srv ArrowMetricsServiceServer) {
	// If the following call pancis, it indicates UnimplementedArrowMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArrowMetricsService_ServiceDesc, srv)
}

func _ArrowMetricsService_ArrowMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArrowMetricsServiceServer).ArrowMetrics(&grpc.GenericServerStream[BatchArrowRecords, BatchStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArrowMetricsService_ArrowMetricsServer = grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]

// ArrowMetricsService_ServiceDesc is the grpc.ServiceDesc for ArrowMetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArrowMetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opentelemetry.proto.experimental.arrow.v1.ArrowMetricsService",
	HandlerType: (*ArrowMetricsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ArrowMetrics",
			Handler:       _ArrowMetricsService_ArrowMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "opentelemetry/proto/experimental/arrow/v1/arrow_service.proto",
}

const (
	ArrowProfilesService_ArrowProfiles_FullMethodName = "/opentelemetry.proto.experimental.arrow.v1.ArrowProfilesService/ArrowProfiles"
)

// ArrowProfilesServiceClient is the client API for ArrowProfilesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArrowProfilesService is a profiles-only Arrow stream.
type ArrowProfilesServiceClient interface {
	ArrowProfiles(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus], error)
}

type arrowProfilesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArrowProfilesServiceClient(cc grpc.ClientConnInterface) ArrowProfilesServiceClient {
	return &arrowProfilesServiceClient{cc}
}

func (c *arrowProfilesServiceClient) ArrowProfiles(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArrowProfilesService_ServiceDesc.Streams[0], ArrowProfilesService_ArrowProfiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchArrowRecords, BatchStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArrowProfilesService_ArrowProfilesClient = grpc.BidiStreamingClient[BatchArrowRecords, BatchStatus]

// ArrowProfilesServiceServer is the server API for ArrowProfilesService service.
// All implementations must embed UnimplementedArrowProfilesServiceServer
// for forward compatibility.
//
// ArrowProfilesService is a profiles-only Arrow stream.
type ArrowProfilesServiceServer interface {
	ArrowProfiles(grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]) error
	mustEmbedUnimplementedArrowProfilesServiceServer()
}

// UnimplementedArrowProfilesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArrowProfilesServiceServer struct{}

func (UnimplementedArrowProfilesServiceServer) ArrowProfiles(grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]) error {
	return status.Errorf(codes.Unimplemented, "method ArrowProfiles not implemented")
}
func (UnimplementedArrowProfilesServiceServer) mustEmbedUnimplementedArrowProfilesServiceServer() {}
func (UnimplementedArrowProfilesServiceServer) testEmbeddedByValue()                              {}

// UnsafeArrowProfilesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArrowProfilesServiceServer will
// result in compilation errors.
type UnsafeArrowProfilesServiceServer interface {
	mustEmbedUnimplementedArrowProfilesServiceServer()
}

func RegisterArrowProfilesServiceServer(s grpc.ServiceRegistrar, srv ArrowProfilesServiceServer) {
	// If the following call pancis, it indicates UnimplementedArrowProfilesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArrowProfilesService_ServiceDesc, srv)
}

func _ArrowProfilesService_ArrowProfiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArrowProfilesServiceServer).ArrowProfiles(&grpc.GenericServerStream[BatchArrowRecords, BatchStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArrowProfilesService_ArrowProfilesServer = grpc.BidiStreamingServer[BatchArrowRecords, BatchStatus]

// ArrowProfilesService_ServiceDesc is the grpc.ServiceDesc for ArrowProfilesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArrowProfilesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opentelemetry.proto.experimental.arrow.v1.ArrowProfilesService",
	HandlerType: (*ArrowProfilesServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ArrowProfiles",
			Handler:       _ArrowProfilesService_ArrowProfiles_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "opentelemetry/proto/experimental/arrow/v1/arrow_service.proto",
}
